name: Drevmass

options:
    bundleIdPrefix: Aset-Madina
    xcodeVersion: '15.2'
    deploymentTarget: '16.0'
    groupSortPosition: top
    generateEmptyDirectories: true
    minimumXcodeGenVersion: '2.39.1'
    
settings:
    base:
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: 1
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      CURRENT_PROJECT_VERSION: "1.0"
      
targets:
    Drevmass:
      type: application
      platform: iOS
      supportedDestinations: iOS
      deploymentTarget: "16.0"
      settings:
        base:
          TARGETED_DEVICE_FAMILY: 1
          INFOPLIST_FILE: Drevmass/Sources/Info.plist
      sources:
         - path: Drevmass/Sources
           group: Drevmass
         - path: Drevmass/Resources
           group: Drevmass
           excludes:
            - README.md
      info:
        path: Drevmass/Sources/Info.plist
        properties:
          UILaunchStoryboardName: "LaunchScreen.storyboard"
          CFBundleVersion: $(CURRENT_PROJECT_VERSION)
          NSAppTransportSecurity:
            NSAllowsArbitraryLoads: true
          UIAppFonts:
            - SF-Pro-Display-Bold.otf
            - SF-Pro-Display-Semibold.otf
            - SF-Pro-Text-Bold.otf
            - SF-Pro-Text-Medium.otf
            - SF-Pro-Text-Regular.otf
            - SF-Pro-Text-Semibold.otf
          UIApplicationSceneManifest:
            UIApplicationSupportsMultipleScenes: false
            UISceneConfigurations: { UIWindowSceneSessionRoleApplication: [{ UISceneConfigurationName: 'Default Configuration', UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate }] }

      dependencies:
        - package: Alamofire
        - package: KeychainSwift
        - package: SnapKit
        - package: SVProgressHUD
        - package: SwiftyJSON
        - package: PanModal
        - package: SDWebImage
        - package: YouTubePlayerKit

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.9.0
  KeychainSwift:
    url: https://github.com/evgenyneu/keychain-swift
    from: 21.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.7.1
  SVProgressHUD:
    url: https://github.com/SVProgressHUD/SVProgressHUD
    from: 2.3.1
  SwiftyJSON:
    url: https://github.com/SwiftyJSON/SwiftyJSON
    from: 5.0.1
  PanModal:
    url: https://github.com/slackhq/PanModal
    from: 1.2.7
  SDWebImage:
    url: https://github.com/SDWebImage/SDWebImage.git
    from: 5.19.0
  YouTubePlayerKit:
    url: https://github.com/SvenTiigi/YouTubePlayerKit.git
    from: 1.7.0
